trol: cons.h File Reference
cons.h File Reference
#include <stdbool.h>
Typedefs
typedef struct sexp_impl * sexp
Symbolic expression.
Functions
sexp atom (sexp expr)
Predicate to test if expr is an atom.
bool c_bool (sexp expr)
Convert a lisp expression to a C bool.
const char * c_str (sexp atom)
Get an atom's string.
sexp car (sexp cons)
Get the first element of a cons pair.
sexp cdr (sexp cons)
Get the second element of a cons pair.
sexp cons (sexp car, sexp cdr)
Create a cons pair.
sexp eq (sexp expr_a, sexp expr_b)
Compare two atoms.
void gc_sexp (sexp expr)
Garbage collect memory.
sexp symbol (const char *str, int strlen)
Create an atom of a given string.
Detailed Description
Definition in file cons.h.
Typedef Documentation
typedef struct sexp_impl* sexp
Symbolic expression.
The symbolic expression (sexp) is the basic abstract data type of lisp. Expressions may be atoms or cons pairs. The atom() predicate can be used to tell them apart. Sexp's are immutable.
Note:
This typedef is a facade, if you need access to the underlying structure, include cons_impl.h.
Definition at line 36 of file cons.h.
Function Documentation
sexp atom (sexp expr)
Predicate to test if expr is an atom.
Parameters:
expr Arbitrary lisp expression.
Returns:
't if expr is an atom, 'nil otherwise.
Definition at line 78 of file cons_impl.c.
References ATOM_NIL(), ATOM_T(), and sexp_impl::t.
Referenced by eq(), equal(), eval(), pair(), print_dot_notation(), and print_list_notation().
bool c_bool (sexp expr)
Convert a lisp expression to a C bool.
In general, you should prefer to use atom() and eq() as they are. However, from time to time it will be necesssary to wrap them as c_bool(eq(a,b)) or c_bool(atom(p)).
Parameters:
expr Arbitrary lisp.
Returns:
true if expr is 't, false otherwise.
Definition at line 56 of file cons_impl.c.
References sexp_impl::t, and sexp_impl::v.
Referenced by append(), assoc(), eq(), equal(), eval(), pair(), print_dot_notation(), and print_list_notation().
const char* c_str (sexp atom)
Get an atom's string.
This method allows things like printing an atom.
Parameters:
atom A lisp atom.
Returns:
'\0' terminated C string.
Definition at line 68 of file cons_impl.c.
References sexp_impl::t, and sexp_impl::v.
Referenced by eq(), print_dot_notation(), and print_list_notation().
sexp car (sexp cons)
Get the first element of a cons pair.
The name car comes from "Contents of Address Register". Steve Russell, the original lisp implementer, admits it was an uninspired name and suggests, in retrosect, that "first" would have been a better choice.
Parameters:
cons A cons pair, for example the head of a list.
Returns:
The first part of the pair.
Definition at line 113 of file cons_impl.c.
References sexp_impl::v.
Referenced by append(), assoc(), equal(), eval(), pair(), print_dot_notation(), and print_list_notation().
sexp cdr (sexp cons)
Get the second element of a cons pair.
The name cdr comes from "Contents of Decrement Register". Steve Russell, the original lisp implementer, suggests that "rest" would have been a better name.
Parameters:
cons A cons pair, for example the head of a list.
Returns:
The second part of the pair, often the tail of a list.
Definition at line 127 of file cons_impl.c.
References sexp_impl::v.
Referenced by append(), assoc(), equal(), eval(), pair(), print_dot_notation(), and print_list_notation().
sexp cons (sexp expr_a, sexp expr_b)
Create a cons pair.
Because cons's may contain other cons's, they can be used to build quite complex data structures. The most common data structure in lisp is the list which is a simple cons chain. In a list, the first element of a cons, the car, is an atom, the second element of a cons, the cdr, is the next cons.
Parameters:
expr_a Arbitrary lisp.
expr_b arbitrary lisp.
Returns:
The newly constructed cons.
Definition at line 171 of file cons_impl.c.
References cons_impl::l, cons_impl::r, sexp_impl::t, and sexp_impl::v.
Referenced by append(), eval(), and pair().
sexp eq (sexp expr_a, sexp expr_b)
Compare two atoms.
Parameters:
expr_a Arbitrary lisp expression.
expr_b Arbitrary lisp expression.
Returns:
't if expr_a and expr_b are the same atom, 'nil otherwise.
Definition at line 90 of file cons_impl.c.
References atom(), ATOM_NIL(), ATOM_T(), c_bool(), and c_str().
Referenced by assoc(), equal(), eval(), null(), and print_list_notation().
void gc_sexp (sexp expr)
Garbage collect memory.
If expr is a cons, then the car and cdr will be recursively deleted as well if they are no longer needed.
Parameters:
expr The expression to free.
Todo:
Implement garbage collection.
Definition at line 193 of file cons_impl.c.
sexp symbol (const char * str, int len)
Create an atom of a given string.
Atoms are so called because they do not have any sub-parts you can inspect, they cannot be further decomposed.
len is used to allow flexibility when parsing atoms from character buffers. Admittedly, it is a bit annoying when you have a null terminated str.
Parameters:
str A character string buffer.
len Length of str in characters.
Returns:
The atom representing str.
Note:
I wanted to call this method atom() to parallel cons(), but I was already using it for the predicate.
Definition at line 148 of file cons_impl.c.
References sexp_impl::t, and sexp_impl::v.