trol: eval.c File Reference
eval.c File Reference
Lisp interpreter.
#include "eval.h"
#include "constants.h"
#include "utils.h"
Functions
sexp eval (sexp expr, sexp env)
Interpret a lisp expression.
Detailed Description
Lisp interpreter.
The star of the show.
Definition in file eval.c.
Function Documentation
sexp eval (sexp expr, sexp env)
Interpret a lisp expression.
TRoL implements eval in lisp. This implementation is not entirely in lisp because I did not implement quote or cond; they are implemented here by eval.
Parameters:
expr Lisp expression.
env Dictionary of variables in scope.
Returns:
Result of evaluation.
Note:
TRoL adds the entire label expression to the env, I don't know why. This implementation only adds the lambda part.
Definition at line 159 of file eval.c.
References append(), assoc(), atom(), ATOM_ATOM(), ATOM_CAR(), ATOM_CDR(), ATOM_COND(), ATOM_CONS(), ATOM_EQ(), ATOM_LABEL(), ATOM_LAMBDA(), ATOM_NIL(), ATOM_QUOTE(), c_bool(), car(), cdr(), cons(), eq(), eval(), and pair().
Referenced by eval(), and main().