trol: parser.c File Reference
parser.c File Reference
Reading and printing expressions.
#include "parser.h"
#include "constants.h"
#include <stdio.h>
Functions
sexp parse (const char **iter_ref)
Convert a char buffer into an expression.
int print_dot_notation (char *str, size_t len, sexp expr)
Print an expression in dot notation.
int print_list_notation (char *str, size_t len, sexp expr)
Print an expression in list notation.
Detailed Description
Reading and printing expressions.
This module defines methods for converting a C string to an sexp, and converting an sexp to a C string. Printing and reading dot notation and list notation are supported.
Definition in file parser.c.
Function Documentation
sexp parse (const char ** iter_ref)
Convert a char buffer into an expression.
Parse a string into a lisp expression. Handles list and dot notation. Handles quote shorthand.
Parameters:
iter_ref Address of a pointer to start of buffer. *iter_ref points to the character after the last successfully parsed character at return time.
Returns:
Lisp expression.
Definition at line 281 of file parser.c.
Referenced by main().
int print_dot_notation (char * str, size_t len, sexp expr)
Print an expression in dot notation.
Dot notation uses a dot between the members of a cons pair. A cons is written with parentheses around it. For example: (a . (b . c)).
Parameters:
str Buffer.
len Storage capacity of str.
expr Arbitrary lisp expression.
Returns:
Same as snprintf().
Definition at line 53 of file parser.c.
References atom(), c_bool(), c_str(), car(), cdr(), and print_dot_notation().
Referenced by print_dot_notation().
int print_list_notation (char * str, size_t len, sexp expr)
Print an expression in list notation.
List notation is the usual way of writing lisp. It allows (quote expr) to be written as 'expr. Cons chains can be simplified as (a b c) for (a . (b . (c . nil))). If the 'nil in the previous example were a 'd, it would be written (a b (c . d)).
Parameters:
str Buffer.
len Storage capacity of str.
expr Arbitrary lisp expression.
Returns:
Same as snprintf().
Definition at line 114 of file parser.c.
References atom(), ATOM_QUOTE(), c_bool(), c_str(), car(), cdr(), eq(), and print_list_notation().
Referenced by main(), and print_list_notation().