trol: utils.c File Reference
utils.c File Reference
Non-primitive functions required by eval().
#include "utils.h"
#include "constants.h"
Functions
sexp append (sexp list_a, sexp list_b)
Concatenate two lists.
sexp assoc (sexp key, sexp map)
Look up key in map.
sexp equal (sexp expr_a, sexp expr_b)
Compare two lisp expressions.
sexp null (sexp expr)
Test for 'nil.
sexp pair (sexp list_a, sexp list_b)
Build a dictionary.
Detailed Description
Non-primitive functions required by eval().
These functions can be written in terms of the lisp understood by eval() and they make writing eval() simpler. They are used for handling the environment and function arguments.
Definition in file utils.c.
Function Documentation
sexp append (sexp list_a, sexp list_b)
Concatenate two lists.
Create a list by joining two lists together.
Parameters:
list_a A list to become the head of new list.
list_b A list to become the tail of new list.
Returns:
A list with the elements of list_a followed by the elements of list_b.
Definition at line 54 of file utils.c.
References append(), c_bool(), car(), cdr(), cons(), and null().
Referenced by append(), and eval().
sexp assoc (sexp key, sexp map)
Look up key in map.
Parameters:
key An atom.
map A dictionary in the form created by pair().
Returns:
The value associated with key if found, key otherwise.
Definition at line 125 of file utils.c.
References assoc(), ATOM_NIL(), c_bool(), car(), cdr(), and eq().
Referenced by assoc(), and eval().
sexp equal (sexp expr_a, sexp expr_b)
Compare two lisp expressions.
Expressions expr_a and expr_b are equal if they have the same structure.
Parameters:
expr_a A symbolic lisp expression.
expr_b A symbolic lisp expression.
Returns:
't if expr_a and expr_b are isomorphic, 'nil otherwise.
Note:
This function is not used by eval(). Instead, it is useful for testing.
Definition at line 73 of file utils.c.
References atom(), ATOM_NIL(), ATOM_T(), c_bool(), car(), cdr(), eq(), and equal().
Referenced by equal().
sexp null (sexp expr)
Test for 'nil.
Predicate to test for 'nil atom. In lisp, 'nil is used for false and the empty list.
Parameters:
expr Arbitrary lisp symbolic expression.
Returns:
't if expr is the 'nil atom, 'nil otherwise.
Definition at line 40 of file utils.c.
References ATOM_NIL(), and eq().
Referenced by append(), and pair().
sexp pair (sexp list_a, sexp list_b)
Build a dictionary.
Build a dictionary from a list of keys list_a and a list of values list_b. The dictionary is in the same order as list_a; it is not sorted. An example in lisp syntax:
 > (pair '(value key) '(3 definition))
 ((value . 3) (key . definition))
Parameters:
list_a A list of keys.
list_b A list of values.
Returns:
A list of (key . value) pairs.
Definition at line 104 of file utils.c.
References atom(), ATOM_NIL(), c_bool(), car(), cdr(), cons(), null(), and pair().
Referenced by eval(), and pair().